
// const s = 'Hello World!';

// console.log(s.toLowerCase());
// console.log(s.toUpperCase());
// console.log(s.substring (5,12).toUpperCase ());
// console.log(s.split (''));

const s = 'Technology,computers,it,code,hello'
console.log (s.split (','))


// const name = 'mamun';
// const age = 36;
// const hello = `My name is ${name} and i am ${age}`
// console.log(hello);
// console.log(`My name is ${name} and i am ${age}`);